env:
  PYPI_URL: https://test.pypi.org/legacy/
language: python
python:
- '2.7'
install:
- pip install twine
- pip install .
script: ls
before_deploy: "python setup.py sdist"
deploy:
  provider: script
  script: twine upload --repository-url ${PYPI_URL} --username ${PYPI_USER} --password ${PYPI_PASSWORD} dist/*
  on:
    all_branches: true  
