language: python
python:
- '2.7'
install:
- pip install .
script: ls
deploy:
  provider: pypi
  user: piotrszul
  password:
    secure: "XyVZJG4Iufdsuo0tYQIfKVmY8pwcQhh5LH8VfI0Mme5aIH8v+qXt4WcVCiYf3pa83YJqSbRx6d5toMeRk+J2f9aAj6gnBaujDzuE9kKpDpz6ylJdgrbkbBPepLe+jgYS+yXWrFcpQgMZeSee1804RZSXylK/94ZFSybzFyiBqw9ETPUDpqWjhQIn5RdxW50/w0ITITxiIgmO8cfa9jch++XL6ynu/w6RutArrk+ui9TrixTifPKGw7+1cw/Y48PTPyHC+yx/0lnew+frk2ZV+jUtCS2ihUlyL5KbgN2STlBRZcWdYAGALcu8Curxo00jI7rpGdLLeEn9qnHI7yxViVaH/G51aQeJ4CImGL+jrTZQT/DyhEClxIOxhPs5it6k8A+SMTKabjEVhU71irEHOAUtnOarRJ/YC8WKB0Gn7bh87PMSmFlupoM3XAmwo9aclQ1OdYI8sF43yymONp989XGNLK3aNDb05OAysAm47xYYJR/5OXRId//RgI5Yxd+GQzhWblBhf1myphBgnIZ1FIX1EUdr7JWdXtVf1SUwNkOxV4wXW4VfH5c5p/vtJW1SOoSY5CfP8rYan8cFZKqqalc2Z3PA5XhX5Ar2t7JsfFqMlo5Zt4ONJ5/sbm8XJbUXsVZGvderrhk+4mSBQsgx7E4rUsGgj3AoCZE0y9eHllQ="
  on:
    all_branches: true  
  server: https://test.pypi.org/legacy/ 
  distributions: "sdist"
