env:
  PYPI_URL: https://test.pypi.org/legacy/
cache:
  directories:
  - "$HOME/.cache/pip"
#  - "$HOME/.pyenv"
language: java 
python:
- '2.7'
install:
- source ~/virtualenv/python2.7/bin/activate
- python --version
- pip install twine
- pip install .[test]
script: ls
before_deploy: "python setup.py egg_info -b .dev${TRAVIS_BUILD_NUMBER} sdist"
deploy:
  provider: script
  script: twine upload --repository-url ${PYPI_URL} --username ${PYPI_USER} --password ${PYPI_PASSWORD} dist/*
  skip_cleanup: true
  on:
    all_branches: true  
