env:
  PYPI_URL: https://test.pypi.org/legacy/
language: python
python:
- '2.7'
install:
- pip install twine
- pip install .
- pip install .[test]
script: ls
before_deploy: "python setup.py egg_info -b .dev${TRAVIS_BUILD_NUMBER} sdist"
deploy:
  provider: script
  script: twine upload --repository-url ${PYPI_URL} --username ${PYPI_USER} --password ${PYPI_PASSWORD} dist/*
  skip_cleanup: true
  on:
    all_branches: true  
